sudo: false

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

before_script:
  - node --version
  - npm --version

script:
  - npm test

after_script:
  - grunt cover

matrix:
  fast_finish: true

notifications:
  email:
    on_failure: change
